#!/usr/bin/env bash
set -euo pipefail

VERSION=${1:-4.1.16}
TAG="v${VERSION}"
BUNDLE=${BUNDLE_DIR:-dist/qnap-bundle}
RELEASE_DIR="$BUNDLE/v${VERSION}"
ASSET=${ASSET_PATH:-dist/mesh-cos-mcp-qnap-v${VERSION}.zip}
COMMIT=${GITHUB_SHA:-$(git rev-parse HEAD)}
LEGACY_FLAT=0
case "$VERSION" in
  4.1.[0-9]|4.1.10|4.1.11)
    RELEASE_DIR="$BUNDLE"
    LEGACY_FLAT=1
    ;;
esac
BUILD_CONTEXT="$RELEASE_DIR/cos-mcp/build-context"

rm -rf "$BUNDLE" "$ASSET" "$ASSET.sha256"
mkdir -p "$RELEASE_DIR/cos-mcp" "$BUILD_CONTEXT/deployment/qnap"

cp deployment/qnap/compose.yaml "$RELEASE_DIR/cos-mcp/compose.yaml"
cp deployment/qnap/.env.example "$RELEASE_DIR/cos-mcp/.env.example"
cp deployment/qnap/README-QNAP.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/DEPLOYMENT-STEPS.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/CHATGPT-ACCEPTANCE.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/install-checklist.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/upgrade-checklist.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/rollback-checklist.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/backup-restore.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/qnap-environment-probe.sh "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/scripts/*.sh "$RELEASE_DIR/"
cp deployment/qnap-environment.md "$RELEASE_DIR/cos-mcp/"
cp deployment/qnap/DEBUGGING-NOTES-v4.1.3.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-production-preflight.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.4.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.5.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.6.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.7.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.8.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.9.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.10.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-security-review-v4.1.11.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/qnap-security-review-v4.1.12.md ] && cp docs/qnap-security-review-v4.1.12.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/qnap-security-review-v4.1.13.md ] && cp docs/qnap-security-review-v4.1.13.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/qnap-security-review-v4.1.14.md ] && cp docs/qnap-security-review-v4.1.14.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/security-review-v4.1.15.md ] && cp docs/security-review-v4.1.15.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/security-review-v4.1.16.md ] && cp docs/security-review-v4.1.16.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-deployment-observability-standard.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-mcp-502-debugging-v4.1.4.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-release-identity-debugging-v4.1.5.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-image-provenance-envelope-debugging-v4.1.7.md "$RELEASE_DIR/cos-mcp/"
cp docs/qnap-versioned-release-staging-v4.1.11.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/qnap-release-root-bootstrap-v4.1.12.md ] && cp docs/qnap-release-root-bootstrap-v4.1.12.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/qnap-slack-approver-bootstrap-v4.1.13.md ] && cp docs/qnap-slack-approver-bootstrap-v4.1.13.md "$RELEASE_DIR/cos-mcp/"
cp docs/chatgpt-published-app-production-acceptance-v4.1.6.md "$RELEASE_DIR/cos-mcp/"
cp docs/chatgpt-published-app-production-acceptance-v4.1.8.md "$RELEASE_DIR/cos-mcp/"
cp docs/chatgpt-published-app-production-acceptance-v4.1.9.md "$RELEASE_DIR/cos-mcp/"
cp docs/chatgpt-published-app-production-acceptance-v4.1.10.md "$RELEASE_DIR/cos-mcp/"
cp docs/chatgpt-published-app-production-acceptance-v4.1.11.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/chatgpt-published-app-production-acceptance-v4.1.12.md ] && cp docs/chatgpt-published-app-production-acceptance-v4.1.12.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/chatgpt-published-app-production-acceptance-v4.1.13.md ] && cp docs/chatgpt-published-app-production-acceptance-v4.1.13.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/chatgpt-published-app-production-acceptance-v4.1.14.md ] && cp docs/chatgpt-published-app-production-acceptance-v4.1.14.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/chatgpt-published-app-production-acceptance-v4.1.15.md ] && cp docs/chatgpt-published-app-production-acceptance-v4.1.15.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/chatgpt-published-app-production-acceptance-v4.1.16.md ] && cp docs/chatgpt-published-app-production-acceptance-v4.1.16.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.4-qnap-modern-mcp-transport.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.5-qnap-release-identity.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.6-secure-mcp-published-app-identity.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.7-qnap-image-provenance-envelope.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.8-mcp-contract-acceptance.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.9-documentation-closeout.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.10-scheduled-slack-hitl.md "$RELEASE_DIR/cos-mcp/"
cp docs/release-4.1.11-qnap-versioned-release-staging.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/release-4.1.12-qnap-release-root-bootstrap.md ] && cp docs/release-4.1.12-qnap-release-root-bootstrap.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/release-4.1.13-slack-approver-bootstrap.md ] && cp docs/release-4.1.13-slack-approver-bootstrap.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/release-4.1.14-qnap-slack-secret-provisioning.md ] && cp docs/release-4.1.14-qnap-slack-secret-provisioning.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/release-4.1.15-slack-plugin-hitl.md ] && cp docs/release-4.1.15-slack-plugin-hitl.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/release-4.1.16-qnap-restarting-backup.md ] && cp docs/release-4.1.16-qnap-restarting-backup.md "$RELEASE_DIR/cos-mcp/"
cp docs/verification-v4.1.11-qnap-versioned-release-staging.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/verification-v4.1.12-qnap-release-root-bootstrap.md ] && cp docs/verification-v4.1.12-qnap-release-root-bootstrap.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/verification-v4.1.13-slack-approver-bootstrap.md ] && cp docs/verification-v4.1.13-slack-approver-bootstrap.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/verification-v4.1.14-qnap-slack-secret-provisioning.md ] && cp docs/verification-v4.1.14-qnap-slack-secret-provisioning.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/verification-v4.1.15-slack-plugin-hitl.md ] && cp docs/verification-v4.1.15-slack-plugin-hitl.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/verification-v4.1.16-qnap-restarting-backup.md ] && cp docs/verification-v4.1.16-qnap-restarting-backup.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/engineering-contract-v4.1.15.md ] && cp docs/engineering-contract-v4.1.15.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/implementation-plan-v4.1.15.md ] && cp docs/implementation-plan-v4.1.15.md "$RELEASE_DIR/cos-mcp/"
[ -f docs/slack-agent-protocol.md ] && cp docs/slack-agent-protocol.md "$RELEASE_DIR/cos-mcp/"
cp specs/qnap-published-chatgpt-app-v4.1.6.feature "$RELEASE_DIR/cos-mcp/"
cp specs/qnap-image-provenance-envelope-v4.1.7.feature "$RELEASE_DIR/cos-mcp/"
cp specs/qnap-mcp-production-acceptance-v4.1.8.feature "$RELEASE_DIR/cos-mcp/"
cp specs/qnap-release-closeout-v4.1.9.feature "$RELEASE_DIR/cos-mcp/"
cp specs/scheduled-automation-slack-hitl-v4.1.10.feature "$RELEASE_DIR/cos-mcp/"
cp specs/qnap-versioned-release-staging-v4.1.11.feature "$RELEASE_DIR/cos-mcp/"
[ -f specs/qnap-release-root-bootstrap-v4.1.12.feature ] && cp specs/qnap-release-root-bootstrap-v4.1.12.feature "$RELEASE_DIR/cos-mcp/"
[ -f specs/qnap-slack-approver-bootstrap-v4.1.13.feature ] && cp specs/qnap-slack-approver-bootstrap-v4.1.13.feature "$RELEASE_DIR/cos-mcp/"
[ -f specs/qnap-slack-secret-provisioning-v4.1.14.feature ] && cp specs/qnap-slack-secret-provisioning-v4.1.14.feature "$RELEASE_DIR/cos-mcp/"
[ -f specs/qnap-slack-plugin-hitl-v4.1.15.feature ] && cp specs/qnap-slack-plugin-hitl-v4.1.15.feature "$RELEASE_DIR/cos-mcp/"
[ -f specs/qnap-restarting-backup-v4.1.16.feature ] && cp specs/qnap-restarting-backup-v4.1.16.feature "$RELEASE_DIR/cos-mcp/"
cp RELEASE.md SECURITY.md "$RELEASE_DIR/cos-mcp/"
printf 'tag=%s\nversion=%s\ncommit=%s\n' "$TAG" "$VERSION" "$COMMIT" > "$RELEASE_DIR/cos-mcp/release-metadata.txt"

cp Dockerfile pyproject.toml .dockerignore "$BUILD_CONTEXT/"
cp -R agents chatgpt config contracts src mcp "$BUILD_CONTEXT/"
cp deployment/qnap/runtime_preflight.py "$BUILD_CONTEXT/deployment/qnap/runtime_preflight.py"
cp deployment/qnap/sqlite_backup.py "$BUILD_CONTEXT/deployment/qnap/sqlite_backup.py"
rm -rf "$BUILD_CONTEXT/mcp/node_modules" "$BUILD_CONTEXT/mcp/dist"
find "$BUILD_CONTEXT" -type d -name __pycache__ -prune -exec rm -rf {} +
find "$BUILD_CONTEXT" -type f -name '*.pyc' -delete

test ! -e "$RELEASE_DIR/cos-mcp/.env"
test ! -e "$RELEASE_DIR/cos-mcp/.env.runtime"
test ! -e "$RELEASE_DIR/cos-mcp/secrets"
test ! -e "$RELEASE_DIR/cos-mcp/state"
test -f "$BUILD_CONTEXT/Dockerfile"
test -f "$BUILD_CONTEXT/mcp/package-lock.json"
test -f "$BUILD_CONTEXT/mcp/src/slack-socket-mode.ts"
test -f "$BUILD_CONTEXT/src/mesh_cos/mcp_runtime.py"
test -f "$BUILD_CONTEXT/src/mesh_cos/mcp_validation.py"
test -f "$BUILD_CONTEXT/src/mesh_cos/slack_hitl.py"
test -f "$BUILD_CONTEXT/src/mesh_cos/slack_socket_approval.py"
test -f "$BUILD_CONTEXT/src/mesh_cos/slack_socket_bridge.py"
test -f "$BUILD_CONTEXT/chatgpt/mcp/tool-input-schemas.v1.json"
test -f "$BUILD_CONTEXT/deployment/qnap/runtime_preflight.py"
test -f "$RELEASE_DIR/mesh-cos-qnap-layout.sh"
test -f "$RELEASE_DIR/mesh-cos-qnap-compose.sh"
test -f "$RELEASE_DIR/mesh-cos-qnap-observability.sh"
test -f "$RELEASE_DIR/mesh-cos-qnap-permissions.sh"
test -f "$RELEASE_DIR/mesh-cos-qnap-image-provenance.sh"
test -f "$RELEASE_DIR/mesh-cos-slack-hitl-configure.sh"
test -f "$RELEASE_DIR/cos-mcp/qnap-security-review-v4.1.11.md"
test -f "$RELEASE_DIR/cos-mcp/qnap-versioned-release-staging-v4.1.11.md"
test -f "$RELEASE_DIR/cos-mcp/release-4.1.11-qnap-versioned-release-staging.md"
test -f "$RELEASE_DIR/cos-mcp/verification-v4.1.11-qnap-versioned-release-staging.md"
test -f "$RELEASE_DIR/cos-mcp/chatgpt-published-app-production-acceptance-v4.1.11.md"
test -f "$RELEASE_DIR/cos-mcp/qnap-versioned-release-staging-v4.1.11.feature"
test -f "$RELEASE_DIR/cos-mcp/release-metadata.txt"
test -f "$RELEASE_DIR/cos-mcp/SECURITY.md"

if [ "$VERSION" = "4.1.12" ]; then
  test -f "$RELEASE_DIR/cos-mcp/qnap-security-review-v4.1.12.md"
  test -f "$RELEASE_DIR/cos-mcp/qnap-release-root-bootstrap-v4.1.12.md"
  test -f "$RELEASE_DIR/cos-mcp/release-4.1.12-qnap-release-root-bootstrap.md"
  test -f "$RELEASE_DIR/cos-mcp/verification-v4.1.12-qnap-release-root-bootstrap.md"
  test -f "$RELEASE_DIR/cos-mcp/chatgpt-published-app-production-acceptance-v4.1.12.md"
  test -f "$RELEASE_DIR/cos-mcp/qnap-release-root-bootstrap-v4.1.12.feature"
fi

if [ "$VERSION" = "4.1.13" ]; then
  test -f "$RELEASE_DIR/cos-mcp/qnap-security-review-v4.1.13.md"
  test -f "$RELEASE_DIR/cos-mcp/qnap-slack-approver-bootstrap-v4.1.13.md"
  test -f "$RELEASE_DIR/cos-mcp/release-4.1.13-slack-approver-bootstrap.md"
  test -f "$RELEASE_DIR/cos-mcp/verification-v4.1.13-slack-approver-bootstrap.md"
  test -f "$RELEASE_DIR/cos-mcp/chatgpt-published-app-production-acceptance-v4.1.13.md"
  test -f "$RELEASE_DIR/cos-mcp/qnap-slack-approver-bootstrap-v4.1.13.feature"
fi

if [ "$VERSION" = "4.1.14" ]; then
  test -f "$RELEASE_DIR/mesh-cos-slack-hitl-provision.sh"
  test -f "$RELEASE_DIR/mesh-cos-qnap-secret-input.sh"
  test -f "$RELEASE_DIR/mesh-cos-tunnel-key-provision.sh"
  test -f "$RELEASE_DIR/cos-mcp/qnap-security-review-v4.1.14.md"
  test -f "$RELEASE_DIR/cos-mcp/release-4.1.14-qnap-slack-secret-provisioning.md"
  test -f "$RELEASE_DIR/cos-mcp/verification-v4.1.14-qnap-slack-secret-provisioning.md"
  test -f "$RELEASE_DIR/cos-mcp/chatgpt-published-app-production-acceptance-v4.1.14.md"
  test -f "$RELEASE_DIR/cos-mcp/qnap-slack-secret-provisioning-v4.1.14.feature"
fi

if [ "$VERSION" = "4.1.15" ]; then
  test -f "$RELEASE_DIR/mesh-cos-slack-hitl-provision.sh"
  test -f "$RELEASE_DIR/mesh-cos-qnap-secret-input.sh"
  test -f "$RELEASE_DIR/mesh-cos-tunnel-key-provision.sh"
  test -f "$RELEASE_DIR/cos-mcp/security-review-v4.1.15.md"
  test -f "$RELEASE_DIR/cos-mcp/engineering-contract-v4.1.15.md"
  test -f "$RELEASE_DIR/cos-mcp/implementation-plan-v4.1.15.md"
  test -f "$RELEASE_DIR/cos-mcp/release-4.1.15-slack-plugin-hitl.md"
  test -f "$RELEASE_DIR/cos-mcp/verification-v4.1.15-slack-plugin-hitl.md"
  test -f "$RELEASE_DIR/cos-mcp/chatgpt-published-app-production-acceptance-v4.1.15.md"
  test -f "$RELEASE_DIR/cos-mcp/qnap-slack-plugin-hitl-v4.1.15.feature"
  test -f "$RELEASE_DIR/cos-mcp/slack-agent-protocol.md"
  ! grep -q 'MESH_COS_SLACK_VERIFIER_TOKEN_FILE' "$RELEASE_DIR/cos-mcp/compose.yaml"
  ! grep -q 'slack-verifier-token' "$RELEASE_DIR/cos-mcp/compose.yaml"
  ! grep -q 'xoxb-' "$RELEASE_DIR/mesh-cos-slack-hitl-configure.sh"
  ! grep -q 'xoxb-' "$RELEASE_DIR/mesh-cos-slack-hitl-provision.sh"
fi

if [ "$VERSION" = "4.1.16" ]; then
  test -f "$RELEASE_DIR/mesh-cos-slack-hitl-provision.sh"
  test -f "$RELEASE_DIR/mesh-cos-qnap-secret-input.sh"
  test -f "$RELEASE_DIR/mesh-cos-tunnel-key-provision.sh"
  test -f "$RELEASE_DIR/cos-mcp/security-review-v4.1.16.md"
  test -f "$RELEASE_DIR/cos-mcp/release-4.1.16-qnap-restarting-backup.md"
  test -f "$RELEASE_DIR/cos-mcp/verification-v4.1.16-qnap-restarting-backup.md"
  test -f "$RELEASE_DIR/cos-mcp/chatgpt-published-app-production-acceptance-v4.1.16.md"
  test -f "$RELEASE_DIR/cos-mcp/qnap-restarting-backup-v4.1.16.feature"
  grep -q '{{.State.Status}}' "$RELEASE_DIR/mesh-cos-mcp-backup.sh"
  grep -q '{{.State.Restarting}}' "$RELEASE_DIR/mesh-cos-mcp-backup.sh"
  grep -q 'quiesced_helper' "$RELEASE_DIR/mesh-cos-mcp-backup.sh"
  grep -q -- '--network none' "$RELEASE_DIR/mesh-cos-mcp-backup.sh"
  ! grep -q 'MESH_COS_SLACK_VERIFIER_TOKEN_FILE' "$RELEASE_DIR/cos-mcp/compose.yaml"
  ! grep -q 'slack-verifier-token' "$RELEASE_DIR/cos-mcp/compose.yaml"
  ! grep -q 'xoxb-' "$RELEASE_DIR/mesh-cos-slack-hitl-configure.sh"
  ! grep -q 'xoxb-' "$RELEASE_DIR/mesh-cos-slack-hitl-provision.sh"
fi

chmod +x "$RELEASE_DIR"/*.sh "$RELEASE_DIR/cos-mcp/qnap-environment-probe.sh"
mkdir -p "$(dirname "$ASSET")"
if [ "$LEGACY_FLAT" -eq 1 ]; then
  (cd "$BUNDLE" && zip -qr "$OLDPWD/$ASSET" .)
else
  (cd "$BUNDLE" && zip -qr "$OLDPWD/$ASSET" "v${VERSION}")
fi
ASSET_BASENAME=$(basename "$ASSET")
ASSET_SHA256=$(sha256sum "$ASSET" | awk '{print $1}')
printf '%s  %s\n' "$ASSET_SHA256" "$ASSET_BASENAME" > "$ASSET.sha256"
echo "bundle=$ASSET"
echo "checksum=$ASSET.sha256"
