import http, { type IncomingMessage, type ServerResponse } from 'node:http';
import { randomUUID } from 'node:crypto';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { isInitializeRequest } from '@modelcontextprotocol/sdk/types.js';
import { callPythonBridge } from './python-bridge.js';
import { createServer, loadContract, requireAgentId } from './server.js';
const MAX_BODY=1_000_000; const MAX_SESSIONS=8;
function ip(req:IncomingMessage):string { return (req.socket.remoteAddress??'').replace(/^::ffff:/,''); }
function allowed(req:IncomingMessage,env:NodeJS.ProcessEnv):boolean { const expected=env.MCP_TRUSTED_CLIENT_IP?.trim(); return Boolean(expected)&&ip(req)===expected; }
async function body(req:IncomingMessage):Promise<unknown>{ let size=0; const chunks:Buffer[]=[]; for await(const c of req){ const b=Buffer.isBuffer(c)?c:Buffer.from(c); size+=b.length; if(size>MAX_BODY) throw new Error('request_too_large'); chunks.push(b); } if(size===0) return undefined; return JSON.parse(Buffer.concat(chunks).toString('utf8')); }
function json(res:ServerResponse,status:number,value:unknown){ const out=JSON.stringify(value); res.writeHead(status,{'content-type':'application/json','content-length':Buffer.byteLength(out)}); res.end(out); }
async function runtimeReady(env:NodeJS.ProcessEnv):Promise<void>{ const contract=loadContract(); const agent=requireAgentId(contract,env); const r=await callPythonBridge({tool_name:'registry.get_agent',arguments:{agent_id:agent}},env); const record=r.result as {status?:string}; if(record?.status!=='ACTIVE') throw new Error('bound_agent_not_active'); await callPythonBridge({tool_name:'governance.verify_audit_chain',arguments:{}},env); }
export async function startRemote(env:NodeJS.ProcessEnv=process.env){ if((env.MCP_AUTH_MODE??'').trim()!=='tunnel') throw new Error('Remote MCP requires MCP_AUTH_MODE=tunnel; controlled HTTPS OAuth is not enabled by this deployment'); if(!env.MCP_TRUSTED_CLIENT_IP?.trim()) throw new Error('MCP_TRUSTED_CLIENT_IP is required'); await runtimeReady(env); const transports=new Map<string,StreamableHTTPServerTransport>(); const app=http.createServer(async(req,res)=>{ try { const url=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`); if(url.pathname==='/healthz'){ return json(res,200,{ok:true}); } if(url.pathname==='/readyz'){ try{ await runtimeReady(env); return json(res,200,{ok:true}); }catch{return json(res,503,{ok:false});} } if(url.pathname!=='/mcp') return json(res,404,{error:'not_found'}); if(!allowed(req,env)) return json(res,403,{error:'forbidden'}); const sessionHeader=typeof req.headers['mcp-session-id']==='string'?req.headers['mcp-session-id']:undefined; let transport=sessionHeader?transports.get(sessionHeader):undefined; let parsed:unknown=undefined; if(req.method==='POST') parsed=await body(req); if(!transport&&req.method==='POST'&&isInitializeRequest(parsed)){ if(transports.size>=MAX_SESSIONS) return json(res,503,{error:'session_limit'}); let created!:StreamableHTTPServerTransport; created=new StreamableHTTPServerTransport({sessionIdGenerator:()=>randomUUID(),onsessioninitialized:id=>{ transports.set(id,created); }}); created.onclose=()=>{ if(created.sessionId) transports.delete(created.sessionId); }; await createServer(env).connect(created); transport=created; } if(!transport) return json(res,400,{error:'invalid_session'}); await transport.handleRequest(req,res,parsed); } catch(error){ if(!res.headersSent) json(res,error instanceof Error&&error.message==='request_too_large'?413:400,{error:'invalid_request'}); else res.end(); } }); const port=Number(env.MCP_PORT??'8080'); const host=env.MCP_BIND_HOST??'0.0.0.0'; await new Promise<void>((resolve,reject)=>{ app.once('error',reject); app.listen(port,host,()=>resolve()); }); const stop=async()=>{ await new Promise<void>(resolve=>app.close(()=>resolve())); for(const t of transports.values()) await t.close(); }; process.once('SIGTERM',()=>void stop().finally(()=>process.exit(0))); process.once('SIGINT',()=>void stop().finally(()=>process.exit(0))); return app; }
await startRemote();
